apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8.2.1
          ports:
            - containerPort: 6379
