apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:24.04
      command: ["sleep", "infinity"]
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "ubuntu"
      effect: "NoSchedule"
