apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-2
  namespace: depi
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
