apiVersion: v1
kind: ResourceQuota
metadata:
  name: depi-qouta
  namespace: depi
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
    requests.cpu: "1"
    requests.memory: 500Mi
    pods: "1"
