apiVersion: v1
kind: Pod
metadata:
  name: nginxandubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep"]
      args: ["infinity"]
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
